import 'package:e_shop/modules/landing/cubit/landing_cubit.dart';
import 'package:e_shop/modules/landing/cubit/landing_states.dart';
import 'package:e_shop/shared/components/builders/myConditional_builder.dart';
import 'package:e_shop/shared/components/reusable/padding/main_padding.dart';
import 'package:e_shop/shared/components/reusable/spaces_and_dividers/spaces.dart';
import 'package:e_shop/modules/landing/model/landing_model.dart';
import 'package:e_shop/shared/components/reusable/text/custom_text.dart';
import 'package:e_shop/styles/constants/constants.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:smooth_page_indicator/smooth_page_indicator.dart';

part 'landing_builder.dart';
part 'landing_build_previewer.dart';
part 'landing_build_welcome.dart';
part 'landing_decoration.dart';
part 'landing_skip_button.dart';
part 'landing_get_started_title.dart';
